// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package storage

import (
	context "context"
	common "github.com/zikwall/blogchain/src/protobuf/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	WritePostStats(ctx context.Context, in *PostStats, opts ...grpc.CallOption) (*common.EmptyResponse, error)
	GetPostViewersCount(ctx context.Context, in *PostViewersRequest, opts ...grpc.CallOption) (*PostViewersResponse, error)
	GetPostsViewersCount(ctx context.Context, in *PostsViewersRequest, opts ...grpc.CallOption) (*PostsViewersResponse, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) WritePostStats(ctx context.Context, in *PostStats, opts ...grpc.CallOption) (*common.EmptyResponse, error) {
	out := new(common.EmptyResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/WritePostStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetPostViewersCount(ctx context.Context, in *PostViewersRequest, opts ...grpc.CallOption) (*PostViewersResponse, error) {
	out := new(PostViewersResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetPostViewersCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetPostsViewersCount(ctx context.Context, in *PostsViewersRequest, opts ...grpc.CallOption) (*PostsViewersResponse, error) {
	out := new(PostsViewersResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetPostsViewersCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	WritePostStats(context.Context, *PostStats) (*common.EmptyResponse, error)
	GetPostViewersCount(context.Context, *PostViewersRequest) (*PostViewersResponse, error)
	GetPostsViewersCount(context.Context, *PostsViewersRequest) (*PostsViewersResponse, error)
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) WritePostStats(context.Context, *PostStats) (*common.EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WritePostStats not implemented")
}
func (UnimplementedStorageServer) GetPostViewersCount(context.Context, *PostViewersRequest) (*PostViewersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostViewersCount not implemented")
}
func (UnimplementedStorageServer) GetPostsViewersCount(context.Context, *PostsViewersRequest) (*PostsViewersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostsViewersCount not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s grpc.ServiceRegistrar, srv StorageServer) {
	s.RegisterService(&Storage_ServiceDesc, srv)
}

func _Storage_WritePostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).WritePostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/WritePostStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).WritePostStats(ctx, req.(*PostStats))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetPostViewersCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostViewersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetPostViewersCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetPostViewersCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetPostViewersCount(ctx, req.(*PostViewersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetPostsViewersCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsViewersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetPostsViewersCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetPostsViewersCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetPostsViewersCount(ctx, req.(*PostsViewersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Storage_ServiceDesc is the grpc.ServiceDesc for Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WritePostStats",
			Handler:    _Storage_WritePostStats_Handler,
		},
		{
			MethodName: "GetPostViewersCount",
			Handler:    _Storage_GetPostViewersCount_Handler,
		},
		{
			MethodName: "GetPostsViewersCount",
			Handler:    _Storage_GetPostsViewersCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
